# Generated by Django 4.1 on 2022-08-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default='Author', max_length=255),
            preserve_default=False,
        ),
    ]
