# Generated by Django 4.1 on 2022-08-10 20:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0004_userbookrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='readers',
            field=models.ManyToManyField(through='book.UserBookRelation', to=settings.AUTH_USER_MODEL),
        ),
    ]
