# Generated by Django 4.1 on 2022-08-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_userbookrelation_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookrelation',
            name='discount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
