# Generated by Django 4.1 on 2022-08-16 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_book_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='discount',
        ),
    ]
